# For ./mvnw spring-boot:run
###
POST http://localhost:8080/shortest-path
Content-Type: application/json

{
  "grid": [
    [1, 1, 1, 1, 1],
    [0, 0, 1, 0, 1],
    [1, 1, 1, 1, 1],
    [1, 0, 0, 0, 1],
    [1, 1, 1, 1, 1]
  ]
}

### 
GET http://localhost:8080/actuator/prometheus

### 
GET http://localhost:8080/actuator





