name: Java CI with Maven
env:
  VERSION: '0.0.3'

on:
  pull_request:
    branches:
      - main
      - develop
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file shortest-path-app/pom.xml

      - name: Login to Docker Hub (assuming secrets are stored)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t taaesan/shortest-path-app:${{ env.VERSION }} shortest-path-app
          docker tag taaesan/shortest-path-app:${{ env.VERSION }} taaesan/shortest-path-app:latest

      - name: Push Docker Image
        run: |
          docker push taaesan/shortest-path-app:${{ env.VERSION }}
          docker push taaesan/shortest-path-app:latest

